### ISSUE TITLE
cannot use close brace key in c++ file

### ISSUE THREAD

**Issue by wsbky** [tweekmonster/deoplete-clang2#9] opened 2017-03-01 15:05 UTC
I cannnot use close brace key in c++ file.
When I push it, the deoplete-clang2 raises errors.

#### please refer
[Screen Shot](https://github.com/wsbky/picture/blob/master/img/screenshot3.png)

**Comment by tweekmonster** [comment] 2017-03-01 15:34
@wsbky Have you update it recently?  This should be resolved in #3. 

If it's still a problem, can you show me the value of `b:clang2_orig_maps`?

**Comment by wsbky** [comment] 2017-03-01 15:40
I can update it with the  
:call dein#update  
command, right?

**Comment by tweekmonster** [comment] 2017-03-01 16:11
> I can update it with the :call dein#update command, right?

I'm not sure.

> I didn't set the b:clang2_orig_maps. Where can I check that value?

In the `c++` buffer, run `:echo b:clang2_orig_maps`

**Comment by wsbky** [comment] 2017-03-02 08:22
```
{'s': ['', {'expr': 1, 'rhs': 'neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)": "\<TAB>"'}], 'i': ['', {'expr': 1, 'rhs': 'pumvisible() ? "\<C-n>" : neosnippet#expandable_or_jum
'}]}e() ?    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"'}], ']': [']'], 'n': ['', {'expr': 0, 'rhs': ':call dein#install()
```

I found that the errors are raised in the tmux sessions. (I detached tmux session and open cpp buffer and I could input ']'

**Comment by tweekmonster** [comment] 2017-03-02 13:08
I'm not sure if that came out right.  Could you do this in a `c++` buffer instead:

```vim
:put=strtrans(string(b:clang2_orig_maps))
```

That will make it easier to copy and paste here.

**Comment by wsbky** [comment] 2017-03-02 14:32
```
{'s': ['', {'expr': 1, 'rhs': 'neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)": "\<TAB>"'}], 'i': ['', {'expr': 1, 'rhs': 'neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)": pumvisible() ? "\<C-n>" : "\<TAB>"'}], ']': [']'], 'n': ['', {'expr': 0, 'rhs': ':call dein#install()^M'}]}

```

**Comment by tweekmonster** [comment] 2017-03-02 16:29
Thanks, I know what the problem is now and will look into it.

**Closed** 2017-03-02 16:39 UTC
Labels: bug

**Comment by wsbky** [comment] 2017-03-02 22:54
Thanks!
